In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("0000000000002417_training_boston_x_y_train.csv", delimiter=",")

In [3]:
data

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,-0.204929,-0.487722,1.231945,3.668398,0.434551,2.161728,1.053485,-0.833960,-0.523001,-0.031105,-1.736418,0.361122,-1.504494,50.0
375,0.231398,-0.487722,1.015999,-0.272599,1.367490,0.215644,0.687212,-0.703186,1.661245,1.530926,0.806576,-2.812183,0.499991,14.3
376,-0.408311,-0.487722,0.247057,-0.272599,-1.016689,-0.206055,-0.809889,0.140451,-0.523001,-0.060801,0.113032,0.332066,-0.334043,20.8
377,-0.410620,-0.487722,-1.152214,-0.272599,-0.818007,0.068904,-1.826921,0.674814,-0.637962,0.129256,-0.719220,0.203235,-0.744752,22.6
378,0.342909,-0.487722,1.015999,3.668398,0.659147,1.041946,1.028593,-1.232462,1.661245,1.530926,0.806576,0.387875,-1.358713,50.0

In [4]:
Y=data[' Y']
del data[' Y']

In [5]:
lc=np.ones(data.shape[0])
lc.shape
data['lc']=lc

In [6]:
points=np.array(data)
points.shape

(379, 14)

In [7]:
def step_gradient(points, learning_rate, m):
    m_slope = np.zeros(14)
    M = len(points)
    for i in range(M):
        x = points[i]
        y = Y[i]
        for j in range(14):
            m_slope[j] = m_slope[j]+(-2/M)* (y - (m * x).sum() )*x[j]
            
    for j in range(14):
        m[j] = m[j] - learning_rate*m_slope[j]
    
    return m

In [8]:
def gd(points, learning_rate, num_iterations):
    m=np.zeros(14)
    for i in range(num_iterations):
        m = step_gradient(points, learning_rate, m)
        print(i, " Cost: ", cost(points, m))
    return m

In [9]:
def cost(points, m):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = points[i]
        y = Y[i]
        total_cost += (1/M)*((y - (m*x).sum() )**2)
    return total_cost

In [10]:
def run():
    learning_rate = 0.1
    num_iterations = 100
    m = gd(points, learning_rate, num_iterations)
    print(m)
    return m

In [23]:
m=run()

0  Cost:  374.24035597919686
1  Cost:  245.37909656079904
2  Cost:  165.10614192173668
3  Cost:  114.49508621191686
4  Cost:  82.43432664281796
5  Cost:  62.041704688310936
6  Cost:  49.0154746660482
7  Cost:  40.65519326019772
8  Cost:  35.25972835067592
9  Cost:  31.754121492629718
10  Cost:  29.457161634001743
11  Cost:  27.936007022144533
12  Cost:  26.914922412896374
13  Cost:  26.217802951980175
14  Cost:  25.731872822963105
15  Cost:  25.38469911771804
16  Cost:  25.129603525591076
17  Cost:  24.936384410518777
18  Cost:  24.785404792037365
19  Cost:  24.66381822190748
20  Cost:  24.56315514362143
21  Cost:  24.477776518190055
22  Cost:  24.403881200700226
23  Cost:  24.338867434896198
24  Cost:  24.280921148348455
25  Cost:  24.228749732407817
26  Cost:  24.18140930058519
27  Cost:  24.138192120101166
28  Cost:  24.09855285948923
29  Cost:  24.06205993819115
30  Cost:  24.028363158977218
31  Cost:  23.997171942483217
32  Cost:  23.968240497783352
33  Cost:  23.941357557710433
34  Cost:  23.916339140893513
35  Cost:  23.8930233395274
36  Cost:  23.871266478618274
37  Cost:  23.8509402167778
38  Cost:  23.83192930414061
39  Cost:  23.81412980765422
40  Cost:  23.797447675836793
41  Cost:  23.781797555694713
42  Cost:  23.767101801312183
43  Cost:  23.753289631473613
44  Cost:  23.740296405677086
45  Cost:  23.728062996050767
46  Cost:  23.716535238305664
47  Cost:  23.705663448792908
48  Cost:  23.695401997540312
49  Cost:  23.685708929185047
50  Cost:  23.676545625233352
51  Cost:  23.667876502228165
52  Cost:  23.659668741294816
53  Cost:  23.651892045237435
54  Cost:  23.644518419921997
55  Cost:  23.63752197714234
56  Cost:  23.630878756545357
57  Cost:  23.624566564510328
58  Cost:  23.61856482814464
59  Cost:  23.612854462787237
60  Cost:  23.607417751606427
61  Cost:  23.602238236046126
62  Cost:  23.597300616021258
63  Cost:  23.592590658888106
64  Cost:  23.58809511632606
65  Cost:  23.583801648361966
66  Cost:  23.579698753854302
67  Cost:  23.575775706825468
68  Cost:  23.57202249809743
69  Cost:  23.568429781741976
70  Cost:  23.564988825906966
71  Cost:  23.561691467625852
72  Cost:  23.558530071255525
73  Cost:  23.555497490223704
74  Cost:  23.552587031798264
75  Cost:  23.54979242461791
76  Cost:  23.547107788749056
77  Cost:  23.54452760805564
78  Cost:  23.542046704688318
79  Cost:  23.53966021551766
80  Cost:  23.537363570351094
81  Cost:  23.53515247178877
82  Cost:  23.53302287658537
83  Cost:  23.530970978397175
84  Cost:  23.528993191804343
85  Cost:  23.527086137506817
86  Cost:  23.52524662860241
87  Cost:  23.52347165786203
88  Cost:  23.521758385925132
89  Cost:  23.52010413034386
90  Cost:  23.51850635541158
91  Cost:  23.51696266271513
92  Cost:  23.515470782356683
93  Cost:  23.514028564794035
94  Cost:  23.51263397325362
95  Cost:  23.511285076672532
96  Cost:  23.50998004313109
97  Cost:  23.50871713373932
98  Cost:  23.507494696943347
99  Cost:  23.506311163222136
[-0.90123085  0.64469871 -0.19650066  0.80238633 -2.07703901  2.39698211
  0.09640491 -2.8992826   2.05232765 -1.16833159 -2.22295196  0.58092984
 -4.25492114 22.67687788]

In [24]:
df=pd.read_csv("0000000000002417_test_boston_x_test.csv")

df[1]=np.ones(df.shape[0])

In [25]:
y_test=[]
x1=np.array(df)
M = x1.shape[0]
for i in range(M):
    x = x1[i]
    z=(m*x).sum()
    y_test.append(z)

In [26]:
add_row=df.columns
add_row
row=[]
for i in add_row:
    row.append(float(i))
row=np.array(row)
z=(row*m).sum()
z

12.315242722559217

In [27]:
y_test.insert(0,z)

In [28]:
y_test=np.array(y_test)
y_test.shape

(127,)

In [29]:
np.savetxt('boston_gradient_decent.csv', y_test, delimiter=',',fmt='%1.5f')